services:
  kuma-pusher:
    build: .
    dns:
      - 10.1.0.2
    container_name: kuma-pusher
    restart: unless-stopped

    # Linux: host networking is simplest for LAN DNS + ICMP behavior
    network_mode: host

    # Allow ICMP (ping) without running as root
    cap_add:
      - NET_RAW

    environment:
      INTERVAL: "5"
      PING_COUNT: "1"
      PING_TIMEOUT_S: "1"
      FORCE_IPV4: "true"
      SEND_DOWN: "true"

      # One per line: host|push_base_url (no query string needed)
      MONITORS: |
        Pixel-8-Johann.fritz.box|https://uptime-kuma.schauer.to/api/push/OxmNfD7hmk
        Pixel-8-Elisabeth.fritz.box|https://uptime-kuma.schauer.to/api/push/KNmJ8PmRRZ
        s7.lan|https://uptime-kuma.schauer.to/api/push/jEyukRTSt9?status=up&msg=OK&ping=
        uplink2.lan|https://uptime-kuma.schauer.to/api/push/xwG98XRM5tEaNHK4mj1Mxkxu2OCaRk62?status=up&msg=OK&ping=

